travis:
  secure:
    BINSTAR_TOKEN: g5LJYnFSknEPF0iq0SXMZRx2d1ydxeSWCCw8NNbyKFWQAXX9qStzh2UqTF0KMv4GSBtJMcf1t7VJ5Dfqq006XHWX8SoA4W5QMioVM9BcJ5aGlWfFXgsD3zz4KN5aHIZu/rP/6IkVO7ERnmJFJBw1zQ92GNUQR6v9Zh91e9UNoJihWvaNrV+6cTs3WnquYanPnbgbFnmDlJ+afr9Hgh0Igq12XNXyTVKe40+o36KS4QDLRfVxpNro19bx7Xu5tw2wYIpaj1gM9RbT6j6ZPwdvymuLcapy0eF0W3aDPjLfhgsf8CpYvK5RosBaue8m9X0eOlCcUUlbszalDYc1IfTgro63J4E06anW4Y3yGbnekmu0JcdqXtxlRa2jsjEbW0VEaq7fcvpr1ej6qRumktOLAun01pMrfNsNg+OXaE9c2lE97FEpqIviNqg5VBKHHVQ6WbOjwGDXFDiGqChmr1BTbwsBbevOjlsXbBtcY12Ihmk+7V/Wi9pZPGA25oCRKd2K9/G9MEy9cS82V0I2xaD5ykZ7WZlF8q8N8yh09lkue9q7O20iF2IuJJujzBVya9+B5ikQbAMZIonU9pn73ZrB0SfN4+M5r2XenxxsAYe3pAItF3uusLmWB0OLIpAf/WX0k29S0MVvTZgYzXLxeL4MhyngILOTJ2rEXxQj2+aBH3U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
